### ISSUE TITLE
Support for kSktScanPropIdDataConfirmationMode

### ISSUE THREAD

**Issue by cnormand127** [SocketMobile/scanapi-cordova#3]
Hi, Does this plugin support the kSktScanPropIdDataConfirmationMode property? and If not any plan on adding it? Thank you

**Comment by EricGlaenzer** [comment]
Hi @cnormand127, this current version of scanapi-cordova does not support any other features other than scanner presence notification, the decoded data notification, initialize complete, terminate and error notifications.
I am evaluating the time it would take to add, in a basic form, a set and get a property APIs which could be used in order to work with the Data Confirmation mode. I'll update on a possible ETA in the next couple of days.

**Comment by cnormand127** [comment]
Thank you, that would be a great feature!

**Comment by EricGlaenzer** [comment]
We are not going to add this feature in ScanAPI for Cordova as we have just release our new Capture SDK, and moving forward we are going to support Capture for Cordova and this feature will be supported.
